{{- if eq .Values.vineyard.volumeType "persistentVolumeClaim" }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vineyard.persistVolumeClaimName }}
  labels:
    {{- include "vineyard.labels" . | nindent 4 }}
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.vineyard.size }}
  storageClassName: {{ .Values.vineyard.storageClass }}
  accessModes:
{{ toYaml .Values.vineyard.accessModes | trim | indent 4 }}
  selector:
    matchLabels:
      {{- include "vineyard.selectorLabels" . | nindent 6 }}

{{- end }}
