apiVersion: v1
kind: Service
metadata:
  name: {{ include "vineyard.fullname" . }}-rpc
  labels:
    {{- include "vineyard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: vineyard-ipc
      protocol: TCP
      name: vineyard-ipc
  selector:
    {{- include "vineyard.selectorLabels" . | nindent 4 }}
